### ISSUE TITLE
2019/4/12 最新进展

### ISSUE THREAD

**Issue by zomux** [tdweiquan/tdw#1]

**Comment by bigdoghc** [comment]
测试一下评论能不能用

**Comment by iamjia** [comment]
大群指导大家创建 github 账号，效仿 996.icu，加油！！！

**Comment by a2647668** [comment]
这英文版看着费劲

**Comment by xiahongy53** [comment]
可靠就OK 英文摸索着来。

**Comment by meiguixiaomi** [comment]
支持

**Comment by panjbjb** [comment]
辛苦了，只能来这里了

**Comment by Wendy9233** [comment]
走到这步，真是不容易啊

**Comment by lwcloud** [comment]
这样搞早晚githup也得墙，，，，

**Comment by pineappleok** [comment]
继续等第9、10个跌停

**Comment by Leonliu121** [comment]
希望是奢侈品，但绝不是无法触及的。加油债委会！

**Comment by jilinbo** [comment]
加油

**Comment by kerwinpeng** [comment]
可以把授权书加到 git里面

**Comment by ljx9999** [comment]
大家团结一致 争取最好的结果

**Comment by cnafzyx** [comment]
辛苦辛苦~全家损失本金（纯）达200万元，很是无奈，希望债委会能给我们讨回说法！

ps：我认为在这里不用避讳什么，github作为程序员的开源基地，给封了，真的是天理难容了~

**Comment by qiya1218** [comment]
加油加油！特别棒！

**Comment by net123ok** [comment]
授权书 还有邮寄地址 去哪看 ？

**Comment by xiongshiran** [comment]
真的是辛苦zwh的人员了，努力就会有回报，我点一个star

**Comment by devid13601367591** [comment]
授权书里受托人空着，可能很多人会有疑虑。会影响人数。

**Comment by Dover999** [comment]
After reading your notice, I fell the same way with all you guys. It not only matters the losing money but more importantly matters the fare issues and the freedom environment in our mother country. Your efforts and contributions will be like what Martin Luther King did which are recorded in history. If everyone leaves it alone, then our country will never move forward. Let's fight against the ugly, negative and black side. One bright and promising future will come on the conditions that we take the actions to stop the wrong things happening.

**Comment by serena6666** [comment]
这里可以加好友群？

**Comment by zerolzg** [comment]
这个怎么还有人发英文的，有人看不懂的吧，另外委托书呢，各个群里发的也不知道对不对

**Comment by amanda0328** [comment]
刚注册完，还不太会使用。谢谢各位的努力，加油！

**Comment by simao1234** [comment]
怎么➕进组

**Comment by qiushi209** [comment]
辛苦各位先锋了！
