### ISSUE TITLE
针对授权书的两个疑问

### ISSUE THREAD

**Issue by sunfriendli** [tdweiquan/tdw#37]
首先，作为出借人再次感谢ZWH为我们22万出借人付出的一切。
1、债委会代表成员是否可以公开？债委会的职责是和政府合法沟通，既然是合法的应该不需要过多的信息保密，而且最初债委会选举是有相关人员信息的。授权书正文提到的代表有：平安大姐、老于...等，据我了解平安大姐等已经很久没有消息了。
2、正文提到“代本人向有关单位或部门递交诉求”，请问具体诉求是什么？我请求公开诉求内容。

**Comment by brandonzhou** [comment]
同样疑问： zwh里面的代表是不是各区域的群众选举出来拥护的代表？
