### ISSUE TITLE
zwh

### ISSUE THREAD

**Issue by damonflycloud** [tdweiquan/tdw#72]
zwh

**Comment by vectorbottom** [comment]
> zwh一直叫我们寄授权书,说什么破万就可以直接跟zy对话,现在不是已经够了么,怎么没发声了!

ZWH现在被威胁，不好太露面，工作还是在开展！

**Comment by TDW201999** [comment]
更新下网站还是可以的啊，又不用你们露面~！给大家说一下最新进展啊~！

**Comment by xf865965128** [comment]
度日如年呀

**Comment by leonzx829** [comment]
希望ZWH工作一切顺利，慢慢推进吧，着急也没有用！

**Comment by dj9399** [comment]
唉，ZWH技术还是不到位，这就是不重视安全的后果啊，在墙国，你只要泄漏了IP、电话，J C 分分钟上门找你喝茶
我看这个地方要凉了
